<?php

/**
 * @file
 * Adds some custom fields for collecting info during the registration process for 
 * Philly Grad Campaign's trainer section
 */


/**
 * Implementation of hook_user().
 */

function pgc_profile_user($op, &$edit, &$user, $category = NULL) {
	switch($op) {
		case 'register':
			$fields['pgc_profile'] = array(
				'#type' => 'fieldset',
				'#title' => t('Contact Information')
			);
			$fields['pgc_profile']['first_name'] = array(
				'#type' => 'textfield',
				'#title' => t('First Name')
			);
			$fields['pgc_profile']['last_name'] = array(
				'#type' => 'textfield',
				'#title' => t('Last Name')
			);
		return $fields;
	}
	break;
}