<?php

/**
 * @file
 * Provides a block that returns a simple JS calendar
 */

/**
 * Implementation of hook_init()
 */

function pgc_calendar_init() {
	drupal_add_js(drupal_get_path('module', 'pgc_calendar') .'/calendar.js');
}

/**
 * Implmentation of hook_block()
 */

function pgc_calendar_block($op = 'list', $delta = 0, $edit = array()) {
	switch($op) {
		case 'list':
			$block[0]['info'] = t('Sidebar Calendar');
			$block[0]['cache'] = BLOCK_NO_CACHE;
			return $block;
			
		case 'view':
			$content = '<div class="calendar" id="calendar-1"></div>';
			$block['subject'] = t('Sidebar Calendar');
			$block['content'] = $content;
			return $block;
		break;
	}
}